### ISSUE TITLE
Create ENV parameters for users

### ISSUE THREAD

**Issue by maltegrosse** [function61/holepunch-server#8]
seems like "hp" is hardcoded - would be nice to have dynamic users:
https://github.com/function61/holepunch-server/blob/master/pkg/holepunchsshserver/sshd.go#L55

**Comment by joonas-fi** [comment]
By "dynamic users" do you mean multiple users, or just a single dynamic username?

I'm not sure multiple users are required, but I can understand wanting to change the username. I added support for that: https://github.com/function61/holepunch-server/commit/deaa44f9005500563e18974c3977b09354279abb
